CR-4 feat: added pre-pushhh

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,10 +2,16 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 #!/bin/sh
-branch="$(git rev-parse --abbrev-ref HEAD)"
-if [ "$branch" = "main" | "develop" ]; then
-  echo "You can't commit directly to main branch"
-  exit 1
-fi
+# branch="$(git rev-parse --abbrev-ref HEAD)"
+# if [ "$branch" = "main" ]; then
+#   echo "You can't commit directly to main branch"
+#   exit 1
+# fi
+
+# if [ "$branch" = "develop" ]; then
+#   echo "You can't commit directly to develop branch"
+#   exit 1
+# fi
 
 npx lint-staged
+npx validate-branch-name
